### PR TITLE
Logging: Bug fixes on file handlers and fixed test script for handlers.

### PR DESCRIPTION
**Pull request by stlehmann**
This PR fixes errors in message formatting with FileHandler and RotatingFileHandler. Also it modifies `test_handler.py` to deal with formatters.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the submission, will look as time permits. A quick note right away - please see if you'd like an "author =" entry in metadata.txt for yourself. If so, please include that change too (as a separate commit please).

**Comment by stlehmann** [comment]
> Please see if you'd like an "author =" entry in metadata.txt for yourself. If so, please include that change too (as a separate commit please).

Thanks, I added the author information and also increased the version number.

**Comment by pfalcon** [comment]
Thanks, merged! Released as 0.5 though. And I went ahead and made test_handlers.py pass on CPython, then applied needed changes (trivial) back to our version.

Merry Christmas!

**Comment by stlehmann** [comment]
Great, thanks for the review. 

Merry Christmas to you, too. Enjoy the holiday.

**Pull request closed without merging**
