### PR TITLE
urequests: Fix bug in redirects using json input

### PR DESCRIPTION
**Pull request by markmelvin**
When using json input, data would be set and the assert on line 77 would fail on a redirect.

### CODE REVIEW

**Comment by pfalcon** [comment]
Good catch, but why ujson.dumps(json) again and again in this case at all, and workaround that with _data? Let's move it out of the loop altogether. Let me know if you'd like to give that a try.

**Comment by markmelvin** [comment]
Sure - I'll make that change.

**Comment by pfalcon** [comment]
Squashed, made commit message more detailed and updated it per https://github.com/pfalcon/micropython-lib/blob/master/CONTRIBUTING.md, and merged, thanks.

**Comment by markmelvin** [comment]
Thanks, Paul!  I'll keep those guidelines in mind next time. Thanks for all your efforts on this project.

**Pull request closed without merging**
