### PR TITLE
Logging: Achieve CPython compliancy with test

### PR DESCRIPTION
**Pull request by stlehmann**
The flush command was missing so the test couldn't work on CPython. I fixed this for the FileHandler class and removed the compliancy note from the test as it is no longer necessary.

### CODE REVIEW

**Comment by pfalcon** [comment]
Is that really all what's needed? I see at least 2 major disrepancies with CPython's version:

1. Their logging record is well, a real record. We have just a (preformatted) string.
2. Default format for logging messages differs (unless I really mix up things).

Btw, if you want to continue on elaborating logging, I'd suggest to look at allowing to set custom format, I guess many users would want that. As usual, starting with a subset of CPython's functionality  in that regard is ok (no need to support all fields it offers).

**Comment by stlehmann** [comment]
With this PR I was targetting mainly on making the test pass on CPython. So that is achieved now by explicitly calling the `flush()` method of the *file object*. This seems to happen automatically on Micropython if you call `write()` but not on CPython. Both seem to work a bit different under the hood here.

I know the  logging module is much more complex in CPython than our micropython version so yes I'd like to elaborate on logging as I think it is a really important module especially on a microcontroller where you have no possibility to use a debugger. I will gladly have a look at setting custom formats. This was one thing I already had in mind.

**Comment by pfalcon** [comment]
Well, I suspected there's some confusion ;-). Try following:

1. Copy your test_handlers.py to some other dir (so CPython's logging is used, not MicroPython's).
2. Run `python3 test_handlers.py`.
3. Observe the failure.

For me it's:

~~~
Traceback (most recent call last):
  File "test_handlers.py", line 47, in <module>
    assert strm._data == res
AssertionError
~~~

That's how we should test stuff - a test run against MicroPython and micropython-lib should behave identical as the same test run against CPython and its stdlib.

Mind also what's written in https://github.com/pfalcon/micropython-lib/wiki/ContributorGuidelines : 

> Prefer taking (and porting) tests from CPython rather than duplicating effort and making your own.

**Comment by pfalcon** [comment]
(To state the obvious: there's no need to drop everything and make that test pass on both CPython and MicroPython now. However, that should be the direction for the future.)

**Comment by pfalcon** [comment]
> I think that's one thing we should add to the contribution guidelines.

Fairly speaking, if you think about it for a bit, that's the only way how it can be ;-). Otherwise, wiki is open for editing if you like. Please make sure that instructions are consistent and not confusing though.

**Comment by pfalcon** [comment]
As mentioned in https://github.com/pfalcon/micropython-lib/pull/23#issuecomment-449646301 , I tweaked test_handlers.py in the way described above. Closing.

**Pull request closed without merging**
